input_dim: 8
hidden_dim: 8
num_class: 4
device: cuda
epoch: 25000
batch_size: 1024
model: lstm_regressor #logistic_regressor,lstm_regressor
num_layers: 5
train_data_path: ../data/train_hk_island_series.pickle #train_hk_island_series.pickle #train_Manhattan_series.pickle
test_data_path: ../data/test_hk_island_series.pickle #test_hk_island_series.pickle #test_Manhattan_series.pickle
eval_epoch: 1
save_epoch: 1
save_best: True
lr: 1e-3
policy: esw
object_num: 4
k: [0.1,0.9,0.9,0.1]
omega: 0.1
policy_update_step: 10
total_history: True
